### PR TITLE
Decode URL given before testing if it's a valid URL

### PR DESCRIPTION
**Pull request by SlimyPanda**
Hi there,

There are specific scenarios where the anonymous redirection doesn't work properly:

When the URL we want to redirect to has an hash (#), the application does not redirect to it as it thinks the # is part of anon.to's URL. This is a normal behavior.

People who want to anonymously redirect to a link with an hash should encode the parameter.

If you give http://local.dev/test%23anchor to the application, it works correctly.

But usually, a developer will use encoding function like PHP's urlencode. And if you do that on the previous URL, it gives you: http%3A%2F%2Flocal.dev%2Ftest%23anchor

The application does not consider it a valid URL and does not redirect.

Same goes when the URL is fully encoded, e.g.: http://local.dev/test#anchor -> %68%74%74%70%3a%2f%2f%6c%6f%63%61%6c%2e%64%65%76%2f%74%65%73%74%23%61%6e%63%68%6f%72

I've created 7 unit tests for the previous cases and the two described above fail:

- When the param is encoded with functions such as urlencode()
- When the param is fully encoded.

One solution is to decode the URL before testing if it's a valid URL. That's what this pull request is about: I modified the index method of the HomeController to decode the URL.

After that all 7 tests passed.

### CODE REVIEW

**Comment by abixalmon** [comment]
Redirecting to hashed url is handled by javascript

```
(function(){
    if(window.location.hash) {
        document.getElementsByName('url')[0].setAttribute('content', '0; url={{ $url }}' + window.location.hash);
    }
})();
```

**Comment by SlimyPanda** [comment]
Do you have an example for a URL where that javascript is triggered?
Because `http://anon.to/?http://local.dev/test#anchor` only redirects me to `http://local.dev/test`.

Same goes, e.g., `https://flat.io/edu#google-classroom`.

**Comment by abixalmon** [comment]
https://anon.to?https://flat.io/edu#google-classroom

https://anon.to/8sKwrO

**Comment by abixalmon** [comment]
It seems to not work in firefox, I will try to fix it later

**Pull request merged**
